✨ ENHANCE: 2 make README file relevant and useful
Abdullah-dev1/react-portfoilo pull request #12
Opened 2024-12-05 18:39 UTC by Abdullah-dev1

2024-12-06 15:15 UTC, connect-bilal requested changes
Please review your work thoroughly before submitting the PR.

2024-12-06 15:15 UTC, connect-bilal commented on README.md
> +- [web-vitals](https://www.npmjs.com/package/web-vitals)
Remove Web vitals.

2024-12-06 15:15 UTC, connect-bilal commented on README.md
> +    /index.html
Some files don't include a / at the start, and that's inconsistent.

2024-12-06 15:15 UTC, connect-bilal commented on README.md
> +## Technical documentation
D should be in Uppercase

2024-12-06 15:15 UTC, connect-bilal commented on README.md
> +For a live demo visit, https://muhammad-abdullah-portfolio-62tl7y4i3.vercel.app
Showing 404 page

2024-12-06 15:15 UTC, connect-bilal commented on README.md
> +cd react-portfoilo
Check spellings, also check repository name carefully.
portfoilo -> portfolio

2024-12-20 15:17 UTC, connect-bilal requested changes
Unnecessary changes.

2024-12-24 16:15 UTC, Abdullah-dev1 commented
Declined

2024-12-24 16:15 UTC, closed without merging