:sparkles: IMPROVE: 1-improve-asset-management
Abdullah-dev1/react-portfoilo pull request #6
Opened 2024-11-19 20:06 UTC by Abdullah-dev1

2024-11-20 06:11 UTC, connect-bilal requested changes
Overall changes looks good. Just minor adjustments required. Nice Work!

2024-11-20 06:11 UTC, connect-bilal commented on src/components/header/CTA.jsx
> +        href="https://docs.google.com/document/d/1wctCQrFqjGCS9nr7dytPnAluL8aXJZ2c/edit?usp=sharing&ouid=110828699296883501870&rtpof=true&sd=true"
Google doc link is not public.

2024-11-20 06:11 UTC, connect-bilal commented on src/assets/image.js
> +export { default as portfolio1 } from './portfolio1.png';
Image could be descriptive. Avatar 1, 2, 3... is not looks good. Same for other images.

2024-11-22 09:19 UTC, Abdullah-dev1 commented on src/components/header/CTA.jsx
> +        href="https://docs.google.com/document/d/1wctCQrFqjGCS9nr7dytPnAluL8aXJZ2c/edit?usp=sharing&ouid=110828699296883501870&rtpof=true&sd=true"
i have resolved this issue please check

2024-11-23 09:58 UTC, merged